[package]
name = "rfc-5424-test"
version = "0.2.0"
edition = "2021"

[dependencies]
syslog_rfc5424 = "0.9"
tracing = "0.1.36"
tracing-rfc-5424 = { version = "0.2", path = "../tracing-rfc-5424"}
tracing-subscriber = "0.3.15"
